### ISSUE TITLE
Monitoring / Backup Attributes

### ISSUE THREAD

**Issue by chrisrasco** [rackspace-cookbooks/platformstack#107]

**Comment by chrisrasco** [comment]
By default, you must set these attributes either for the node or the environment or bootstrapping bombs out.

```
"platformstack": {
  "cloud_monitoring": {
    "enabled": false
  },
  "cloud_backup": {
    "enabled": false
  }
}
```

This should be more intuitive. We should do a check for nil values so things work without having to set this. If it's not present, assume enabled is set to false.

**Comment by prometheanfire** [comment]
already fixed :D
