### ISSUE TITLE
Update Consul cookbook for consul-haproxy

### ISSUE THREAD

**Issue by evan4498** [rackspace-cookbooks/platformstack#129]
Add the ability install and configure haproxy and consul-haproxy via the consul cookbook via PR to it

**Comment by kikitux** [comment]
have you seen this?

an initial version of a Consul-HAProxy cookbook, available here:
    https://supermarket.getchef.com/cookbooks/consul-haproxy

**Comment by ghost** [comment]
This exists post-rename of $(née consul-haproxy), and is probably better than my version anyway.
-> http://github.com/adamkrone/chef-consul-template
