### ISSUE TITLE
Configure a logstash agent or rsyslog client

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/platformstack#134]
Add functionality to configure a logstash agent or rsyslog client, if metadata about ELK exists from #133, and ensure the agent or syslog forwards log data to ELK stack nodes.

**Comment by jujugrrr** [comment]
@martinb3 Hi!
I have a couple questions

1.
Is the goal to : 
- have a kind of [feature flag](https://one.rackspace.com/display/GDP/Implement+Feature+Flags+for+Stacks) in platform stack to trigger the chosen install of rsyslog-client or logstash-agent ? 
- write Chef code in platformstack to configure those 2 possible solutions?

I'd vote for the first one, as for me the workflow would be, platformstack is the default config for all servers(you can configure it though), ELKstack is where we define all our logging infrastructure configuration. So platformstack would include elkstack::logstash_agent or elkstack::rsyslog_client, then it's this recipe role to apply AutomationSupport/railsstack#66 / AutomationSupport/pythonstack#92 ...

2.
How do we pick if we want rsyslog or logstash agent ? (is it a customer choice or ours?)

3.
Did we already think about how to implement it? Would the logic be something like that ?

If we want rsyslog client : 
- configure all services/app to use rsyslog, then rsyslog => logstash server
  If we want logstash agent : 
- platformstack/elkstack configure logstash_agent to monitor all services logs (let's say  a logstash_agent config file per service)

4.
How deeply do we want to configure all of that?
- logstash_agent/logstash_server to parse/tags/grep/type? Or just send the raw logs
- rsyslog to send everything as it gets it or something preformated for logstash like => http://untergeek.com/2012/10/11/using-rsyslog-to-send-pre-formatted-json-to-logstash/
  -elasticsearch mapping?
  -kibana dashboards?

It's nice to have the ability to search for logs, it's even better to have the possibility to search on specific fields, sort them, geoip, do ranges and have dashboard with fancy charts :smile: . In addition I think this is how we can demonstrate Rackspace expertise/value :smile:

**Comment by martinb3** [comment]
1. For this item, I think a feature flag would be great, but I think it's important that we don't configure clients using recipes from ELKstack. I think the client logging should be decoupled from our logging infrastructure recipes (the logging 'infrastructure' isn't the logging clients, necessarily). I would not like to have to modify client recipes if doing an ELK cluster upgrade, for example. Also, if we ever wanted to migrate to a different cookbook, it would be much harder if we were configuring clients using elkstack.
2. The issues open on each stack are to identify what else we might need to log. I imagine once we have that list, we' know better if logstash agent is a better fit than syslog, or vice-versa. We can't really do any of this well unless we have identified the log sources aside from syslog itself.
3. See item two of my responses. I don't think we can decide this until we have taken inventory.
4. Again, it depends on what we find in item two of my response. I think once we know _what_, we'll know how we want to configure it.

I agree with you on our value proposition, but I do think we can provide the most value and best parsing if we define ahead of time what kinds of logs might come out of each stack, so I think we need to do those issues first, before solving this one.

**Comment by jujugrrr** [comment]
> I would not like to have to modify client recipes if doing an ELK cluster upgrade, for example

Not sure which upgrade you are talking about, but if you take logstash agent, it's quite tied to the logstash server, so it would make sense to configure in at the same place.

> Also, if we ever wanted to migrate to a different cookbook, it would be much harder if we were configuring clients using elkstack.

So if we don't have elkstack::logstash_agent what would we be alternatives solutions ? 

> The issues open on each stack are to identify what else we might need to log. I imagine once we have that list, we' know better if logstash agent is a better fit than syslog, or vice-versa. We can't really do any of this well unless we have identified the log sources aside from syslog itself.

Oky so I assume it's OUR decision :smile: 

> See item two of my responses. I don't think we can decide this until we have taken inventory.

Fair enough

> but I do think we can provide the most value and best parsing if we define ahead of time what kinds of logs might come out of each stack

:+1: to what you replied to .2/.3/.4 . However without finishing the issues we can quickly think about : 
- apache access/error logs
- mysql logs
- varnish logs
- tomcat / java
- nginx
- redis
- ... and so on

So I'd assume "we will have a lot of logs, in a lot of different formats, not all supporting rsyslog by default, each of them being more useful once parsed". So the other issues are not really a blocker, it's more to have more details

**Comment by martinb3** [comment]
Yes, it's definitely our decision. I just didn't want to get ahead of myself by deciding about agents before we knew about what logs. I guess I would rather see clients/agents configured via platformstack, as (1) people wouldn't necessarily know/remember to include elkstack in every runlist in their whole environment, (2) we could upgrade the elkstack cookbook without worrying about breaking a phpstack client running logstash_agent, for example. I like the idea of loosely coupled client and server configuration code for logging. But I concede that it's probably not much different from doing the clients in elkstack in a separate recipe.

Honestly, maybe the right thing to do is have each stack deposit logstash templates for it's log formats, and let elkstack or platformstack do the rest. But I'd like to avoid having log formatting templates for a large number of logging formats inside elkstack.

**Comment by jujugrrr** [comment]
> Honestly, maybe the right thing to do is have each stack deposit logstash templates for it's log formats, and let elkstack or platformstack do the rest

It sounds good! I just feel platformstack should not handle logic to configure a log_agent.

> people wouldn't necessarily know/remember to include elkstack

People would include platformstack, platformstack would include elkstack:agent recipe. So it works the same way, it's just that we write logstash/client logging code inside the stack which is dedicated to that.

To be honest I'm struggling to understand the whole Stacks scope (for this ELKstack by example), I can just see there is a lot of duplication between Stack, and it's hard to integrate.
