### ISSUE TITLE
Move ohai plugins from rackops_rolebook

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/platformstack#140]
It seems that ohai plugins should be installed by platformstack, not rackops_rolebook. Some of our cookbooks require the ohai plugin data due to specifics about Rackspace, not about support. Additionally, we should update our plugins to include more recent ones like [virtualization](https://github.com/jespada/ohai-plugins/blob/master/virtualization.rb)/[lxc-virtualization](https://github.com/jespada/ohai-plugins/blob/master/lxc_virtualization.rb). This would allow `node.lxc?` in our `locale.rb` recipe, so we could genuinely detect LXC or VMware.

/cc @hhoover since he was interested in our stacks w/ docker.

**Comment by prometheanfire** [comment]
it looks like we moved it to https://github.com/rackerlabs/ohai-plugins.git

closing :D
