### ISSUE TITLE
Move nodestack::format_disk to platformstack

### ISSUE THREAD

**Issue by schwing** [rackspace-cookbooks/platformstack#145]
Actions that will apply to all stacks, like ephemeral disk formatting, should be moved up to platformstack to keep the stacks DRY.

https://github.com/AutomationSupport/nodestack/blob/master/recipes/format_disk.rb

If this code exists elsewhere in other stacks, we should move it out of those as well.

**Comment by prometheanfire** [comment]
it now exists in stack_commons :D
