### ISSUE TITLE
logging recipe fails to discover single node elkstack

### ISSUE THREAD

**Issue by lmunro** [rackspace-cookbooks/platformstack#164]
logging recipe use default elkstack elastic search query to discover logstash server nodes. It uses tags:elkstack_cluster which doesn't discvoer single node elkstack.

We can either change tags:elkstack_cluster to tags:elkstack in platformstac::logging, or add a new search that just looks for logstash in case logstash server is split out onto a different node than elasticsearch.

**Comment by martinb3** [comment]
The search is exposed as an attribute that you can can modify (see [the 6th bullet item here](https://github.com/rackspace-cookbooks/elkstack#things-you-should-know)). We expect many, if not most, customizations will end up overriding that. We don't recommend single-node ELK stacks deployments, so this isn't really the use case we were expecting. If these workarounds don't work, please re-open.
