### ISSUE TITLE
wrong sftp subsystem default

### ISSUE THREAD

**Issue by gdelvalle** [rackspace-cookbooks/platformstack#185]
This attribute below  is wrong for all the OSes that we support/I looked at.
attributes/openssh.rb:
default['openssh']['server']['subsystem'] = 'sftp /usr/libexec/sftp-server'

Here is the location Ubuntu 12.04 and 14.04
/usr/lib/openssh/sftp-server

Here is the location Centos 5 and 6
/usr/libexec/openssh/sftp-server

This breaks any sftp capabilities.  Maybe we can make it conditional based on the distro or we can set it to use internal-sftp as a safe default?

**Comment by theborch** [comment]
Blame Gentoo.

**Comment by theborch** [comment]
Blame Gentoo

**Comment by theborch** [comment]
Blame Gentoo

**Comment by theborch** [comment]
Blame Gentoo

**Comment by theborch** [comment]
Blame Gentoo - @prometheanfire
