### ISSUE TITLE
tmux is not available on Centos by default

### ISSUE THREAD

**Issue by jujugrrr** [rackspace-cookbooks/platformstack#204]
https://github.com/rackspace-cookbooks/platformstack/commit/1214811d13ea4647bf3e953bd74badb6a9770db0 introduced `tmux` as a default package.
However on Centos `tmux` is only available if Epel repo has been configured.

On Rackspace cloud images, Epel is always there by default, however it's not the case on Vagrant images.

It means its not possible to converge platformstack locally anymore : 

```
 No candidate version available for tmux

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/platformstack/recipes/rackops_rolebook.rb

            54:   package admin_package do
            55:     action :install
            56:   end
            57: end
```

**Comment by martinb3** [comment]
I believe this was fixed in #205.
