### ISSUE TITLE
Make yaml_monitors an attribute

### ISSUE THREAD

**Issue by fernandohonig** [rackspace-cookbooks/platformstack#62]
yaml_monitors = %w(
  monitoring-cpu
  monitoring-disk
  monitoring-filesystem
  monitoring-load
  monitoring-mem
  monitoring-net
)

Using yaml_monitors as an attribute, we can add things like:
- Monitoring-mysql
- Monitoring-mssql

Instead of copy&paste the monitoring recipe for lampstack, just add that and call platformstack::monitoring

**Comment by prometheanfire** [comment]
not sure this is possible, I do think that we should crawl hash and look for disabled instead.  Even that I don't think will work though.

This cookbook only controls a couple of monitors, if we starting telling it to control monitors outside of the cookbook how will it know what to do?
