### ISSUE TITLE
monitors.rb -> Alarms setting

### ISSUE THREAD

**Issue by fernandohonig** [rackspace-cookbooks/platformstack#83]

**Comment by fernandohonig** [comment]
I can't find a way to define alarms for each monitor.

I am using for a customer the following:

node.default['rackspace_cloudmonitoring']['monitors'].merge!(
   'ping' => {
     'type' => 'remote.ping',
     'target_alias' => 'access_ip1_v4',
     'monitoring_zones_poll' => %w(mzord mzlon mzdfw),
     'alarm' => {
       'CRITICAL' => { 'conditional' => "metric['available'] < 80", 'message' => 'Packet loss is greater than 20%' },
       'WARNING'  => { 'conditional' => "metric['available'] < 90", 'message' => 'Packet loss is greater than 10%' }
     }
   } )

**Comment by prometheanfire** [comment]
Don't think we have one for ping atm, not sure, but the templates should be mostly self explaitory

**Comment by fernandohonig** [comment]
What I am thinking is to add something like this to this monitors.rb

https://github.com/rackspace-cookbooks/rackspace_cloudmonitoring/blob/master/recipes/monitors.rb

In that case, the customer can create their own alarms based on attributes.
