### ISSUE TITLE
default.rb -> Only apt supported

### ISSUE THREAD

**Issue by fernandohonig** [rackspace-cookbooks/platformstack#84]

**Comment by fernandohonig** [comment]
node.default['apt']['compile_time_update'] = true

include_recipe 'apt::default'

There is no yum support based on platform_family.

**Comment by gondoi** [comment]
This is just to refresh the apt cache. There is no need for something like that in yum. Also, apt will only run if apt is present, otherwise it will skip so it can safely be run on other distros.

**Comment by fernandohonig** [comment]
If in the future, apt cookbook forget to make the check (if apt is installed), this will fail. Can we use platform_family check just to be sure we are loading something that is  supported by the OS?

**Comment by gondoi** [comment]
We should be testing before we release a stable version, but yes, that is probably a good idea.

**Comment by fernandohonig** [comment]
#85 submitted for this.

**Comment by prometheanfire** [comment]
#85 was merged, closing
