### ISSUE TITLE
RackConnect needs password auth

### ISSUE THREAD

**Issue by zdeptawa** [rackspace-cookbooks/platformstack#97]
If node['platformstack']['rackconnect'] = true, we should set default['openssh']['server']['password_authentication'] = 'yes' as RackConnect uses password auth to access the server.

**Comment by martinb3** [comment]
FWIW, we could probably also do this only for the RC user. That's what I've done in Kashoo's:

https://github.com/AutomationSupport/1424144-kashoo_app/blob/master/attributes/default.rb#L4-L13

https://github.com/AutomationSupport/1424144-kashoo_app/blob/master/recipes/ssh.rb#L12-L18

**Comment by prometheanfire** [comment]
I do that like this already :P
